### ISSUE TITLE
Remove LOADERS global?

### ISSUE THREAD

**Issue by rhattersley** [MetOffice/forest#154]
The [forest.data.LOADERS](https://github.com/informatics-lab/forest/blob/v0.4.2/forest/data.py#L34) global seems only to be used in two [adjacent](https://github.com/informatics-lab/forest/blob/v0.4.2/forest/main.py#L130) [places](https://github.com/informatics-lab/forest/blob/v0.4.2/forest/main.py#L151) within the top-level routine (plus a trivial [helper function](https://github.com/informatics-lab/forest/blob/v0.4.2/forest/data.py#L80)).

It would seem we could simplify this to a local variable...?

**Comment by andrewgryan** [comment]
The LOADERS dictionary is how FOREST implements per-server caching. Admittedly this could be improved to be more obvious, perhaps I should write some API docs to explain it.

Bokeh's has two entry points server_lifecycle.py and main.py, each new user/browser tab/web socket gets a main.py called with a Document object, `bokeh.plotting.curdoc()`, the server on start calls a method in server_lifecycle.py. FOREST after start-up holds a single copy of  `data.py` that gets shared between each invocation of main.py. Effectively that LOADERS dict is a low-tech way of keeping a single instance for all users

**Comment by andrewgryan** [comment]
https://bokeh.pydata.org/en/latest/docs/reference/server.html

**Comment by andrewgryan** [comment]
Actually, a  better description can be found here: https://bokeh.pydata.org/en/latest/docs/user_guide/server.html#building-bokeh-applications

**Comment by rhattersley** [comment]
That makes sense - thanks. 👍 I'd wondered if there was some Bokeh magic involved ... should have dug deeper. 😑

In which case, can we be even more aggressive in the caching - the argument parsing & loader creation will be the same for every invocation? (It doesn't look like the View classes are shareable as some of them contain a reference to a mutable `color_mapper`.)

**Comment by andrewgryan** [comment]
I've often wondered whether `server_lifecycle.py` would be a good place to do the command line parsing, I think there is a duplication of parsing for the invocation of the server and then for the invocation of `main.main()`

The `View` classes are constructed for each `document`, since they respond to browser tab specific settings they shouldn't be cached per server. Also, they are very very lightweight, since they just act as mirrors for BokehJS, all of the data should be cached inside the per-server `Loader` singletons.

As for the `color_mapper`, I'd like to de-couple that a little since we want to allow multiple colorbars. For example, a black white bar for satellite cloud measurements underlayed model precip with a separate colorbar, similar tickets are #145 and #146. I should open a new one to address multiple colorbars as it's subtly different
